version: "3"

services:
  abrecipes:
    container_name: abrecipes
    build: .
    command: python3 manage.py runserver 0.0.0.0:5000
    ports:
      - 5000:5000
    restart: always
    env_file:
      - ./.envs/.env-dev
    volumes:
      - ./:/app
